version: '3.6'
services:
  mtproxyweb:
    image: mritd/mtproxyweb
    container_name: mtproxyweb
    networks:
      - nginx
    restart: always
    environment:
      - MT_ADDRESS
      - MT_PORT
      - MT_SECRET
networks:
  nginx:
    external:
      name: nginx
