version: '3.7'
services:
  pre-nginx:
    image: nginx:1.17.3-alpine
    container_name: pre-nginx
    restart: always
    networks:
      - nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"

networks:
  nginx:
    external:
      name: nginx
