version: '3.7'
services:
  numb:
    image: mritd/numb:v1.0.2
    container_name: numb
    restart: always
    networks:
      - nginx
    volumes:
      - "./numb.yaml:/numb.yaml"

networks:
  nginx:
    external:
      name: nginx
