version: '2'
services:
  nginx:
    image: nginx:1.13.8-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./conf.d:/etc/nginx/conf.d
      - ./log/nginx/:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
