version: '3.7'
services:
  jekyll:
    image: mritd/jekyll
    container_name: jekyll
    networks:
      - nginx
    restart: always
  idgen:
    image: mritd/idgen:v1.0.0
    container_name: idgen
    networks:
      - nginx
    restart: always
  jsonon:
    image: mritd/jsonon
    container_name: jsonon
    networks:
      - nginx
    restart: always

networks:
  nginx:
    external:
      name: nginx
