version: '3'
services:
  jekyll:
    image: mritd/jekyll
    container_name: jekyll
    networks:
      - nginx
    restart: always
  radicale:
    image: mritd/radicale:2.1.11
    container_name: 2do
    networks:
      - nginx
    restart: always
    volumes:
      - /data/radicale:/data/radicale
  idea:
    image: mritd/idea
    networks:
      - nginx
    container_name: idea
    restart: always
  idgen:
    image: mritd/idgen:v0.0.3
    container_name: idgen
    networks:
      - nginx
    restart: always
  crxdl:
    image: mritd/crxdl:v1.0.0
    container_name: crxdl
    networks:
      - nginx
    restart: always
  jsonon:
    image: mritd/jsonon
    container_name: jsonon
    networks:
      - nginx
    restart: always
  myip:
    image: mritd/myip:v1.0.0
    container_name: myip
    networks:
      - nginx
    restart: always
  mtproxyweb:
    image: mritd/mtproxyweb
    container_name: mtproxyweb
    networks:
      - nginx
    restart: always
    environment:
      - MT_ADDRESS
      - MT_PORT
      - MT_SECRET
  wechat-markdowner:
    image: mritd/wechat-markdowner
    container_name: wechat-markdowner
    networks:
      - nginx
    restart: always

networks:
  nginx:
    external:
      name: nginx
