version: '3.5'
services:
  chrome-headless:
    image: mritd/chrome-headless
    container_name: chrome-headless
    restart: always
    ports:
      - "9222:9222"
    environment:
      - CHROME_CMD
    command: ${CHROME_CMD}
