# export MT_SECRET=`echo dd$(openssl rand -hex 16)`
version: '3.6'
services:
  mtproxy:
    image: nineseconds/mtg:stable
    container_name: mtproxy
    restart: always
    ports:
      - "118:3128"
    environment:
      - MT_SECRET
    command: ${MT_SECRET}
