version: '3.6'
services:
  mtproxy:
    image: nineseconds/mtg:stable
    container_name: mtproxy
    restart: always
    ports:
      - "118:3129"
    environment:
      - MT_SECRET
    command: ${MT_SECRET}
