version: '3.7'
services:
  cloudreve:
    image: mritd/cloudreve:relativepath
    container_name: cloudreve
    restart: always
    ports:
    - 5212:5212
    volumes:
    - ./config:/etc/cloudreve
    - data:/data
    - shared:/downloads
    command: ["-c","/etc/cloudreve/conf.ini"]
  aria2:
    image: p3terx/aria2-pro
    container_name: aria2
    restart: always
    volumes:
    - shared:/downloads
    environment:
    - TZ=Asia/Shanghai
    - RPC_PORT=6800
    - RPC_SECRET=bleem
    - DISK_CACHE=64M
    - IPV6_MODE=false
    ports:
    - 6800:6800/tcp
    - 6888:6888/tcp
    - 6888:6888/udp
  ariang:
    image: p3terx/ariang
    container_name: ariang
    restart: always
    ports:
    - 6880:6880
volumes:
  shared:
  data:
