version: '3.5'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.0
    container_name: logstash
    restart: always
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./config:/usr/local/logstash/config
      - data:/data
    command: -f /usr/local/logstash/config/logstash.conf
volumes:
  data:
